FROM nvcr.io/nvidia/pytorch:23.05-py3

RUN apt-get update
RUN pip install --upgrade pip

WORKDIR /dcm2nifti-seg/suprem

 # TotalSegmentatorおよび必要なPythonパッケージをインストール
RUN pip install --no-cache-dir monai==0.9.0 connected-components-3d fastremap numpy nibabel h5py==3.6.0